version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
      - "veille"
    reviewers:
      - "{{ github.repository_owner }}"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "veille"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci-cd"
      - "veille"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
